---
- name: Step 1 - Prepare all cluster nodes for K3s
  hosts: all
  become: true
  gather_facts: false
  vars:
    ansible_ssh_timeout: 10
  tasks:
    - name: Enable passwordless sudo for pi user
      ansible.builtin.copy:
        dest: /etc/sudoers.d/010_pi-nopasswd
        content: "pi ALL=(ALL) NOPASSWD:ALL\n"
        mode: '0440'

    - name: Turn off active swap
      ansible.builtin.command:
        cmd: swapoff -a
      ignore_errors: true

    - name: Remove cgroup_disable=memory from Raspberry Pi boot params
      ansible.builtin.replace:
        path: /boot/firmware/cmdline.txt
        regexp: 'cgroup_disable=memory'
        replace: ''
      ignore_errors: true

    - name: Ensure cgroup parameters are present in Raspberry Pi boot params
      ansible.builtin.lineinfile:
        path: /boot/firmware/cmdline.txt
        backrefs: true
        regexp: '^(.*)$'
        line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
      ignore_errors: true