---
- name: Step 1 - Prepare All Nodes for K3s
  hosts: all
  become: true
  tasks:
    - name: Check if dphys-swapfile exists
      stat:
        path: /etc/dphys-swapfile
      register: swapfile_check

    - name: Disable swap memory
      command: dphys-swapfile swapoff
      when: swapfile_check.stat.exists
      ignore_errors: true

    - name: Uninstall dphys-swapfile
      command: dphys-swapfile uninstall
      when: swapfile_check.stat.exists
      ignore_errors: true

    - name: Disable swap service
      ansible.builtin.systemd:
        name: dphys-swapfile
        enabled: false
        state: stopped
      when: swapfile_check.stat.exists
      ignore_errors: true

    - name: Install nfs-common utility
      ansible.builtin.apt:
        name: nfs-common
        state: present
        update_cache: yes

    - name: Check if cgroups file exists on Raspberry Pi OS
      stat:
        path: /boot/firmware/cmdline.txt
      register: rpi_cmdline

    - name: Enable cgroups on Raspberry Pi OS nodes
      replace:
        path: /boot/firmware/cmdline.txt
        regexp: '^((?!.*cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory).*)$'
        replace: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
      when: rpi_cmdline.stat.exists

    - name: Check if cgroups file exists on Armbian (Rock64)
      stat:
        path: /boot/armbianEnv.txt
      register: armbian_env

    - name: Enable cgroups on Armbian node
      lineinfile:
        path: /boot/armbianEnv.txt
        line: 'extraargs=cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
        state: present
      when: armbian_env.stat.exists