all:
  children:
    k3s_cluster:
      hosts:
        pi5zero:
          ansible_host: 192.168.0.150
        pi5one:
          ansible_host: 192.168.0.151
        pi4:
          ansible_host: 192.168.0.152
        rock64:
          ansible_host: 192.168.0.154
    standalone:
      hosts:
        pi2:
          ansible_host: 192.168.0.155
  vars:
    ansible_user: pi